#!/usr/bin/env python3
"""Lift the XPDIR rule core out of the EA and translate it to C++.

The core lives between the XPDIR_RULE_CORE_BEGIN / XPDIR_RULE_CORE_END markers
in FlashGold_Continuation_v2_XPDIR.mq5. It is pure MQL5: no global read, no
runtime call beyond MathAbs / MathIsValidNumber. This script is the same
mechanical MQL5->C++ translation the Shape Map port uses
(XPMap/reference/emu/mql2cpp.py), narrowed to the constructs the core uses:

  const T &name[]   ->  const Arr<T>& name
  T &name[]         ->  Arr<T>& name
  string &out       ->  string& out

Nothing else is rewritten, so what g++ compiles and runs IS the EA's source
text for those functions - not a paraphrase of it.
"""
import re, sys

src = open(sys.argv[1], newline=None).read()

# The grade constants are part of the core's contract, so they come along.
defines = [l for l in src.split("\n")
           if re.match(r"\s*#define\s+XPDIR_GRADE_\w+", l)]
if not defines:
    sys.exit("no XPDIR_GRADE_* defines found in the EA")

begin = src.index("XPDIR_RULE_CORE_BEGIN")
end = src.index("XPDIR_RULE_CORE_END")
body = src[begin:end]
body = body[body.index("\n") + 1:]          # drop the marker line itself

out = []
for line in body.split("\n"):
    if line.strip().startswith("//|") or line.strip().startswith("//+"):
        continue
    line = re.sub(r"(const\s+)?(\w+)\s*&\s*(\w+)\[\]",
                  lambda m: f"{m.group(1) or ''}Arr<{m.group(2)}>& {m.group(3)}", line)
    line = re.sub(r"(\w+)\s+&\s*(\w+)\b(?!\[)", r"\1& \2", line)
    out.append(line)

open(sys.argv[2], "w").write("// generated by extract_core.py - do not edit\n"
                             + "\n".join(defines) + "\n"
                             + "\n".join(out) + "\n")
print(f"extracted {len(out)} lines of MQL5 rule core -> {sys.argv[2]}")
