#!/usr/bin/env python3
"""Lift a marked XPDIR block out of the EA and translate it to C++.

  usage: extract_core.py <ea.mq5> <out.cpp> [MARKER]   (default XPDIR_RULE_CORE)

Blocks live between <MARKER>_BEGIN and <MARKER>_END in
FlashGold_Continuation_v2_XPDIR.mq5:
  XPDIR_RULE_CORE   the vote and rule evaluation - pure MQL5, no global read,
                    no runtime call beyond MathAbs / MathIsValidNumber (Gate 1)
  XPDIR_GATE0_CORE  the entry-path wiring, which does read globals; the Gate 0
                    driver supplies them as stubs and drives them (Gate 0)
This script is the same
mechanical MQL5->C++ translation the Shape Map port uses
(XPMap/reference/emu/mql2cpp.py), narrowed to the constructs the core uses:

  const T &name[]   ->  const Arr<T>& name
  T &name[]         ->  Arr<T>& name
  string &out       ->  string& out

Nothing else is rewritten, so what g++ compiles and runs IS the EA's source
text for those functions - not a paraphrase of it.
"""
import re, sys

src = open(sys.argv[1], newline=None).read()

marker = sys.argv[3] if len(sys.argv) > 3 else "XPDIR_RULE_CORE"

# The grade constants are part of the core's contract, so they come along.
defines = [l for l in src.split("\n")
           if re.match(r"\s*#define\s+XPDIR_GRADE_\w+", l)]
if not defines:
    sys.exit("no XPDIR_GRADE_* defines found in the EA")
if marker != "XPDIR_RULE_CORE":
    defines = []

begin = src.index(marker + "_BEGIN")
end = src.index(marker + "_END")
body = src[begin:end]
body = body[body.index("\n") + 1:]          # drop the marker line itself

out = []
for line in body.split("\n"):
    if line.strip().startswith("//|") or line.strip().startswith("//+"):
        continue
    line = re.sub(r"(const\s+)?(\w+)\s*&\s*(\w+)\[\]",
                  lambda m: f"{m.group(1) or ''}Arr<{m.group(2)}>& {m.group(3)}", line)
    line = re.sub(r"(\w+)\s+&\s*(\w+)\b(?!\[)", r"\1& \2", line)
    out.append(line)

open(sys.argv[2], "w").write("// generated by extract_core.py - do not edit\n"
                             + "\n".join(defines) + "\n"
                             + "\n".join(out) + "\n")
print(f"extracted {len(out)} lines of MQL5 rule core -> {sys.argv[2]}")
