//+------------------------------------------------------------------+
//|                                                   XP ChartEngine |
//|                                         Developed by Coders Guru |
//|                                          Copyrighted for XPWORX |
//|                                          https://www.xpworx.com |
//+------------------------------------------------------------------+
#property service
#property copyright   "xpworx"
#property link        "https://www.xpworx.com"
#property description "XP ChartEngine"
#define  Version      "1.2"
#property version     Version
#property strict

enum ENUM_CUSTOM_SECONDS 
{ 
   S1=1,       // 1 Second
   S2=2,       // 2 Seconds
   S5=5,       // 5 Seconds 
   S10=10,     // 10 Seconds
   S30=30,     // 30 Seconds
   S_Custom=0  // Manual Input
};

input string               BaseSymbol    = "BTCUSD";      
input ENUM_CUSTOM_SECONDS  Timeframe     = S1;            
input int                  ManualSeconds = 15;           
input bool                 UpdateRatesEveryTick = false;

string actual_symbol; 
string custom_name;  
string lock_key;
string heartbeat_key;
double lock_owner = 0.0;
bool lock_acquired = false;

bool AcquireCustomSymbolLock()
{
   lock_key = "XPChartEngine.Lock." + custom_name;
   heartbeat_key = lock_key + ".Heartbeat";
   lock_owner = (double)TimeLocal() * 100000.0 + (double)(GetTickCount() % 100000);

   if(!GlobalVariableCheck(lock_key))
      GlobalVariableSet(lock_key, 0.0);

   double current_owner = GlobalVariableGet(lock_key);
   if(current_owner != 0.0)
   {
      if(GlobalVariableCheck(heartbeat_key))
      {
         datetime last_seen = (datetime)GlobalVariableGet(heartbeat_key);
         if(TimeLocal() - last_seen > 30)
            GlobalVariableSet(lock_key, 0.0);
      }
   }

   ResetLastError();
   if(!GlobalVariableSetOnCondition(lock_key, lock_owner, 0.0))
   {
      Print("XP ChartEngine stopped: ", custom_name, " is already being generated by another service instance.");
      return false;
   }

   lock_acquired = true;
   GlobalVariableSet(heartbeat_key, (double)TimeLocal());
   return true;
}

void TouchCustomSymbolLock()
{
   if(lock_acquired)
      GlobalVariableSet(heartbeat_key, (double)TimeLocal());
}

void ReleaseCustomSymbolLock()
{
   if(!lock_acquired)
      return;

   if(GlobalVariableCheck(lock_key) && GlobalVariableGet(lock_key) == lock_owner)
   {
      GlobalVariableSet(lock_key, 0.0);
      GlobalVariableDel(heartbeat_key);
   }
}

void FillRateBar(MqlRates &rates[], datetime bar_time, double open, double high, double low, double close, long volume, int spread)
{
   rates[0].time = bar_time;
   rates[0].open = open;
   rates[0].high = high;
   rates[0].low = low;
   rates[0].close = close;
   rates[0].tick_volume = volume;
   rates[0].spread = spread;
   rates[0].real_volume = 0;
}

//+------------------------------------------------------------------+
//| Service program start function                                   |
//+------------------------------------------------------------------+
void OnStart()
{
   int interval_s = (Timeframe == S_Custom) ? ManualSeconds : (int)Timeframe;
   if(interval_s <= 0) interval_s = 1;

   // 1. AUTO-DETECT BROKER SUFFIX
   actual_symbol = "";
   for(int i=0; i<SymbolsTotal(false); i++) {
      string sym = SymbolName(i, false);
      if(StringFind(sym, BaseSymbol) >= 0) {
         actual_symbol = sym;
         break;
      }
   }

   if(actual_symbol == "") {
      Print("ERROR: Could not find any broker symbol containing: ", BaseSymbol);
      return;
   }

   // 2. AUTO-GENERATE CUSTOM NAME
   custom_name = actual_symbol + "_S" + (string)interval_s;

   if(!AcquireCustomSymbolLock())
      return;

   // 3. CREATE OR SELECT SYMBOL
   if(!SymbolSelect(custom_name, true)) {
      if(!CustomSymbolCreate(custom_name, "Custom\\XPChart", actual_symbol)) {
         Print("Failed to create custom symbol. Error: ", GetLastError());
         ReleaseCustomSymbolLock();
         return;
      }
      SymbolSelect(custom_name, true);
      CustomSymbolSetInteger(custom_name, SYMBOL_DIGITS, (int)SymbolInfoInteger(actual_symbol, SYMBOL_DIGITS));
   }

   Print("XP ChartEngine Active: ", actual_symbol, " -> ", custom_name);

   MqlTick last_tick;
   MqlRates s_bar[1];
   double bar_open=0, bar_high=0, bar_low=0, bar_close=0;
   long bar_tick_volume=0;
   int bar_spread=0;
   datetime last_bar_time=0;
   datetime last_heartbeat_time=0;
   bool bar_ready=false;
   long last_tick_time_msc = 0; // Filter to avoid redundant updates

//--- Main Loop
   while(!IsStopped()) 
   {
      datetime now = TimeLocal();
      if(now != last_heartbeat_time)
      {
         TouchCustomSymbolLock();
         last_heartbeat_time = now;
      }

      if(SymbolInfoTick(actual_symbol, last_tick)) 
      {
         if(last_tick.time_msc != last_tick_time_msc)
         {
             datetime current_time = TimeCurrent();
             datetime bar_time = (current_time / interval_s) * interval_s;
             int current_spread = (int)((last_tick.ask - last_tick.bid) / SymbolInfoDouble(actual_symbol, SYMBOL_POINT));
             
             if(!bar_ready) {
                bar_open = last_tick.bid;
                bar_high = last_tick.bid;
                bar_low  = last_tick.bid;
                bar_close = last_tick.bid;
                bar_tick_volume = 0;
                bar_spread = current_spread;
                last_bar_time = bar_time;
                bar_ready = true;
             }
             else if(bar_time != last_bar_time) {
                FillRateBar(s_bar, last_bar_time, bar_open, bar_high, bar_low, bar_close, bar_tick_volume, bar_spread);
                CustomRatesUpdate(custom_name, s_bar, 1);

                bar_open = last_tick.bid;
                bar_high = last_tick.bid;
                bar_low  = last_tick.bid;
                bar_close = last_tick.bid;
                bar_tick_volume = 0;
                bar_spread = current_spread;
                last_bar_time = bar_time;
             }
             
             bar_high = MathMax(bar_high, last_tick.bid);
             bar_low  = MathMin(bar_low, last_tick.bid);
             bar_close = last_tick.bid;
             bar_tick_volume++;
             bar_spread = current_spread;

             if(UpdateRatesEveryTick)
             {
                FillRateBar(s_bar, last_bar_time, bar_open, bar_high, bar_low, bar_close, bar_tick_volume, bar_spread);
                CustomRatesUpdate(custom_name, s_bar, 1);
             }

             // B. FIX: Push a Virtual Tick using an ARRAY (Fixes error 113)
             MqlTick tick_to_push[1]; 
             tick_to_push[0] = last_tick;
            tick_to_push[0].time = current_time;
            
            // This function expects: (symbol, array, count)
            CustomTicksAdd(custom_name, tick_to_push, 1);

            last_tick_time_msc = last_tick.time_msc;
         }
      }
      Sleep(100); 
   }

   if(bar_ready)
   {
      FillRateBar(s_bar, last_bar_time, bar_open, bar_high, bar_low, bar_close, bar_tick_volume, bar_spread);
      CustomRatesUpdate(custom_name, s_bar, 1);
   }

   ReleaseCustomSymbolLock();
}
